version: "3"
services:
    php:
        build: .
        ports: 
            - "60080:80"
        volumes: 
            - "./www:/var/www/html"
            - "./busybox:/usr/local/bin/busybox"
    db:
        image: mysql:5.6
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes: 
            - "init.sql:/docker-entrypoint-initdb.d/init.sql"
