<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\web\Controller;

class VerificationController extends Controller
{


    public function actionLogin(){
        return ! YII::$app->user->isGuest();
    }

    public function beforeAction( $action )
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function actionStatus(){
        YII::$app->response->format = "json";
        $username = \YII::$app->user->getId ();
        if($username){
            return ["username"=>$username,"isAdmin"=>intval(User::findOne (["username"=>$username])["isAdmin"] ) == 1];
        }
        return ["error"=>["not login"]];

    }

    public function actionIndex(){
        $username=\YII::$app->request->post ("username");
        $password = \YII::$app->request->post ("password");
        $action = \YII::$app->request->post ("action");
        $result = [];
        YII::$app->response->format = "json";
        if($action==null){
            $result["error"][] = "Null Action";
        }else{
            if($password!=null&&$username!=null&&is_string ($password)&&is_string ($username)){
                $password = User::hash($password);

            }else{
                $result["error"][] = "Password or Username Invalid";
            }
            switch ($action){
                case "login":

                    try{
                        $identity = User::findOne(['username' => $username,'password'=>$password]);

                    }catch (PDOException $exceptione){
                        $result["error"][] = $exceptione->getTraceAsString ();
                        break;
                    }



                    if($identity!==null&&Yii::$app->user->login($identity)){

                        $result["username"] = $identity["username"];
                        $result["isAdmin"] = $identity["isAdmin"];

                    }else{
                        $result["error"][]="账号或密码错误";
                    }

                    break;
                case "register":
                    $u = new User();
                    $u->id = User::find()->max('id')?:0;
                    $u->id ++ ;
                    $u->username = $username;
                    $u->password = $password;
                    $u->validate ();
                    if($u->getErrors ()){
                        \YII::$app->response->setStatusCode (500);
                        return $u->getErrors ();
                    }
                    if(!file_exists ("../installed")){
                        if(is_writeable ("..")===false){
                            $path = pathinfo('..');
                            $result["error"][] = "can't write installed in ".$path['dirname'].$path['basename'];
                            break;
                        }

                        $u->isAdmin = "1";
                        try{
                            $u->save ();
                        }catch (PDOException $exception){
                            $result["error"] = $exception->getTraceAsString ();
                            break;
                        }
                        file_put_contents ("../installed","");
                        $result["info"] = "创建管理员成功";
                    }else{
                        try{
                            $u->save ();
                        }catch (PDOException $exception){
                            $result["error"] = $exception->getTraceAsString ();
                            break;
                        }
                        $result["info"] = "创建用户成功";
                    }

                    break;
            }

        }

        return $result;


    }
}
